spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/tastynote
    username: sa
    password:
    driver-class-name: org.h2.Driver
#  datasource:
#    url: jdbc:postgresql://localhost:5432/tastynote
#    username: chaebyeonghun
#    password:
#    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      enabled: true
      location: ${java.io.tmpdir}
      max-file-size: 1MB
      max-request-size: 1MB

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type.descriptor.sql: trace